kind: pipeline
name: manifest

platform:
  os: linux

steps:
- name: generate tags
  image: alpine
  commands:
  - apk --no-cache add git
  - git fetch --tags
  - echo "$(cat .extratags),$(git describe --tags HEAD | sed -e 's/^v//')" > .tags

- name: manifest
  image: plugins/manifest
  settings:
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password

depends_on: []
