kind: pipeline

platform:
  os: linux

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ghcr.io/rkojedzinszky/alpine-python-grpcio
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
