kind: pipeline
name: build-armhf

platform:
  os: linux
  arch: arm

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: rkojedzinszky/alpine-python-grpcio
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
    auto_tag_suffix: armhf

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: arm

steps:
- name: manifest
  image: plugins/manifest
  settings:
    auto_tag: true
    spec: manifests/manifest.image.tmpl
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password

depends_on:
- build-armhf
